data:
  processed_path: "D:/ML_Services/ml_ETL_project/data/processed/wine_processed.csv"

training:
  n_estimators: 300
  max_depth: 12
  random_state: 42
  n_jobs: -1
  test_size: 0.2   # REQUIRED

mlflow:
  tracking_uri: "file:///D:/ML_Services/ml_ETL_project/mlruns"
  experiment_name: "wine_quality"

paths:
  models: "models"
  reports: "reports"
